### ISSUE TITLE
Importing CSV

### ISSUE THREAD

**Issue by Oddly** [wesselt/bunq2ynab#1]
A possibility to modify bunq2ynab so as to import a manually created CSV (for the free BUNQ users) into YNAB with this script.

**Comment by wesselt** [comment]
@Oddly I've added a script "csv2ynab.py" to upload CSV files to YNAB.

Have you tried YNAB's import though? It's at YNAB's Account -> Import -> Import File and seems to work fine with BUNQ CSV's.
