### ISSUE TITLE
Error message on OSX. No Clue what it means.

### ISSUE THREAD

**Issue by PaulP-Github** [wesselt/bunq2ynab#11]
Hi Wessel, I would like to export for all bunq accounts all transactions via you script, to be manually imported in Banktivity.
When running as a test "python list_user.py" I get the following error message. 

  File "/Users/paul/Documents/bunq2ynab-master/bunq.py", line 96, in get_public_key
    pem = crypto.dump_publickey(crypto.FILETYPE_PEM, private_key)
AttributeError: 'module' object has no attribute 'dump_publickey'

Probably no error on the scipt side, but something I do not understand. Can you advise please.

Thanks, Paul

**Comment by wesselt** [comment]
Hi Paul,

This repository helps import transactions into [YNAB](https://www.youneedabudget.com/). I'm sorry it can't help you with Banktivity. 

Kind regards,
Wessel

**Comment by PaulP-Github** [comment]
Hi Wessel, thank for the reply. I was thinking maybe it was possible to do the export from bunq only and use that as import files. But thanks anyhow. No need to follow up. Thanks Paul
