### ISSUE TITLE
auto_sync.py fails to start: notification_filters was moved

### ISSUE THREAD

**Issue by ghost** [wesselt/bunq2ynab#15]
On October 8th, bunq has removed `notification_filters` from the MonetaryAccount object and introduced separate endpoints: https://beta.doc.bunq.com/basics/changelog#october-8-2019

Due to this change, auto_sync.py now fails to start with the following error:

```
Traceback (most recent call last):
  File "auto_sync.py", line 101, in <module>
    add_callback(port)
  File "auto_sync.py", line 49, in add_callback
    "notification_target": url
  File "auto_sync.py", line 59, in set_autosync_callbacks
    old_nfs = bunq_api.get_callbacks(bunq_user_id, bunq_account_id)
  File "/home/bunq2ynab/bunq2ynab/bunq_api.py", line 34, in get_callbacks
    return result[account_type]["notification_filters"]
KeyError: 'notification_filters'
```

**Comment by wesselt** [comment]
Thanks for letting me know. My auto sync was still running fine, perhaps because it was started before this was changed.

I've updated auto_sync and it should now work with the new endpoints. Works for me, how does it work for you?

**Comment by ghost** [comment]
Thanks for the update. It works fine for me :)
