### ISSUE TITLE
Bunq change on Signing response

### ISSUE THREAD

**Issue by harmlessdonkey** [wesselt/bunq2ynab#19]
Hi,

Seems bunq made a change yesterday which means that the script no longer works. 

Any way we could fix this as I have been relying on this script to keep me on budget!

**Comment by ghost** [comment]
It's fixed already by #17. You must be using an older version, pull master :)

**Comment by harmlessdonkey** [comment]
Yes, that seems to have been it alright. I thought I had updated it already. Did it there and worked fine.

Heart stopped for a while thinking I was going to have to update YNAB manually! Thanks for all your work on this guys!
