### ISSUE TITLE
Restructure the repository with separate `test` and `src` directories.

### ISSUE THREAD

**Issue by an00bhav** [wesselt/bunq2ynab#27]
Hi, 

I would like to propose a change to change the directory structure in a way that it is possible to have the source in one place and then add tests another module which contains unit tests for the code. 

I would also propose to add separate bunq and ynab into their own src directories. 

If you agree to this, I can work on this in my fork and raise a PR. 

Thoughts?

**Comment by wesselt** [comment]
Hi Anubhavcodes,

Thanks for your proposal. If you see an opportunity to add meaningful tests that would be welcome. Creating a separate test directory is fine. The python scripts that are intended to be invoked from the command line should remain in the root of the project.

The "config" branch is currently in its last phase of testing and I'll merge it to master soon. If you want to work on a PR then I would base it on the config branch.

Kind regards,
Wessel

**Comment by an00bhav** [comment]
Thanks a lot @wesselt for your reply. I will wait for your config branch to be merged into `master` and will revisit this issue later. 

Just FYI, we can still have a cli entry point that can be called from the root of the directory like `python -m bunq2ynab <entrypoint>` and still call them from a `src` directory. But we can talk about it later. ;) 

I am closing this issue for now. :)
