### ISSUE TITLE
Only syncing one out of 2 accounts. 

### ISSUE THREAD

**Issue by javydekoning** [wesselt/bunq2ynab#28]
In my config I have 2 accounts, syncing to different budgets. This has stopped working, and I'm not sure why. 

Opening a ticket for myself to research why this is happening.

**Comment by wesselt** [comment]
I added a parameter for ynab_budget_name, might have something to do with it?

**Comment by javydekoning** [comment]
Thanks, I'll look into it now. Any reason you hardcoded the ssmpath instead of using env vars?

**Comment by wesselt** [comment]
Yeah, I didn’t understand how to solve the “recursive” error without removing the env vars. That might be solved now with the HttpApi as its own resource.

Just remembered an issue where a “return” made the synch stop after the first account, here https://github.com/wesselt/bunq2ynab/commit/46d07c604377507d91a363ae989f8380dca4a59b

**Comment by javydekoning** [comment]
Yes, that commit fixed it. 

The circular/recursive error is indeed because the HttpApi was part of the Function. It needs to create the API first before you can reference it. With the template like this, it should work.

I'll keep it running like this for a little bit again, if it's successful I'll publish to Serverless Application Repository and write new instructions.
