### ISSUE TITLE
KeyError: 'MonetaryAccountBank

### ISSUE THREAD

**Issue by beninhos** [wesselt/bunq2ynab#3]
UserPerson "X. Xavier" (99999)
Traceback (most recent call last):
  File "list_user.py", line 21, in <module>
    print_accounts(v["id"])
  File "list_user.py", line 9, in print_accounts
    for a in [a["MonetaryAccountBank"] for a in bunq.get(method)]:
KeyError: 'MonetaryAccountBank

When running list_user.py

**Comment by wesselt** [comment]
Hi beninhos, I've added a -v option so you can run list_user.py with extra options:

    python3 list_user.py -v

Could you run that and see what happens?  For me, it looks like:
```
******************************
GET v1/user/xxx/monetary-account
Status: 200
----------
{
  "Pagination": {
    "older_url": null,
    "future_url": null,
    "newer_url": null
  },
  "Response": [
    {
      "MonetaryAccountBank": {
        "id": xxx,
        "updated": "2018-04-01 19:29:17.213710",
        "country": "NL",
        "sub_status": "NONE",
```
The error message suggests that for you the MonetaryAccountBank is not where it is expected.

**Comment by beninhos** [comment]
Hi Wesselt,

It state like this;

`beninho@jaguar:/pool/data/app/bunq2ynab$ python list_user.py -v
******************************
GET v1/user
Status: 401
----------
{
  "Error": [
    {
      "error_description": "Insufficient authorisation.", 
      "error_description_translated": "Insufficient authorisation."
    }
  ]
}
******************************
Deleting file session_token.txt...
Requesting session token...
`
And then goes further, with a ET v1/user
Status: 200
----------

with grabbing my personal information.  

Lots of junk and then this

`******************************
GET v1/user/xxx/monetary-account
Status: 200
----------
{
  "Pagination": {
    "newer_url": null, 
    "future_url": null, 
    "older_url": null
  }, 
  "Response": [
    {
      "MonetaryAccountBank": {
        "status": "ACTIVE", 
        "sub_status": "NONE", `

**Comment by wesselt** [comment]
There does seem to be a MonetaryAccountBank element. I've added a separate line to "list_user.py" that prints the type of account,. Could you pull the new version and check the output?

Perhaps it might be related to the type of account? Do you have a regular bunq account or a business or joint account?

**Comment by wesselt** [comment]
Can't produce the problem without the information I asked for, closing the issue.
