### ISSUE TITLE
User-entered transactions are not matched

### ISSUE THREAD

**Issue by bibz** [wesselt/bunq2ynab#34]
Hi,

When I manually add transactions to my budget (obviously before they get picked up by the script), the importer mechanism does not match them with the actual bunq transactions.

This also happens with the "recurring" transactions I set up in YNAB (e.g. monthly donations).

It seems that if the importer sees the transaction and can match it in-memory, it simply bails on it and does not propagate the match to YNAB.

AFAIK, and since the importer is stateless, propagating the match to YNAB means being aggressive and incurring duplicates. But as those are handled gracefully by YNAB, I do not see that as a problem.

PS: finding great value in this project, thanks!

**Comment by wesselt** [comment]
Thanks for the report! I'll investigate next week after my holiday.
