### ISSUE TITLE
Faster refresh rate?

### ISSUE THREAD

**Issue by smichaelsen** [wesselt/bunq2ynab#36]
Is there a special reason to only sync every 8 hours? Would I run into API limits at bunq or YNAB if the script ran more often?
I've changed it to 1 hour now for me, and it seems to work (though I didn't wait 24h yet).

Ultimately it would be fun if I could pay in a shop, get into my car and sort the payment from there immediately because the script syncs every other minute, but I guess that would be too much. :)

https://github.com/wesselt/bunq2ynab/blob/4222e55865ad8ecb0ca87c7daaf27b0a646f848f/auto_sync.py#L16

**Comment by javydekoning** [comment]
It already can sync automatically via callbacks. Refer to the "Activating Sync" section in the readme.

If you run local, refer to "Automatic synchronization". The code you link to is for refreshing the port forward/updating the callback function.

**Comment by smichaelsen** [comment]
Now I get what these callbacks are. duh. Thanks, man.
