### ISSUE TITLE
Joint accounts fail to sync

### ISSUE THREAD

**Issue by beninhos** [wesselt/bunq2ynab#40]
I have a joint account. Setup correct. I get this error. 

WARNING | sync.py:90 | populate | No matches for rule "*" - "Gezamelijke rekening" to "April" - "Bunq - Gezamelijk".

In other output, the * is replaced with the 'UserPerson' as per list_user.py  or bunq_user_name as names in sync.py. I think there are the same. 
With the joint account, * is given back and no syncs.  Not sure how to debug this.

**Comment by wesselt** [comment]
Do you see the account if you run the "list_user.py" script?

**Comment by beninhos** [comment]
Yes
Gezamelijke rekening                                    XXXX.XX EUR  ACTIVE     MonetaryAccountJoint      XXXXX

**Comment by wesselt** [comment]
Perhaps it's the joint account... I don't have one.  What do you think of setting up a joint account to test?

**Comment by beninhos** [comment]
sure. Only way to find out then :)

**Comment by wesselt** [comment]
When I add a shared account it's asking for phone number or email... what's the email you use for bunq?

**Comment by beninhos** [comment]
Yes, how can i share this in private?

**Comment by wesselt** [comment]
Not sure how you can send private messages on github. My bunq email is xxx, can you create a shared account based on that?

**Comment by beninhos** [comment]
Sure. I'll invite you! Was looking for PM too.

**Comment by wesselt** [comment]
Zie hem binnenkomen, "Connect accepted".  Ik zal vandaag of morgen wat testen.

**Comment by wesselt** [comment]
Voor mij werkt het goed, heb een cent gestort en die komt in YNAB.

In mijn list_user.py staat de account als:

` Deelrekening                                              0.00 EUR  ACTIVE     MonetaryAccountBank       6316733`

Bij jou stond hij als  MonetaryAccountJoint.

Misschien maakt het uit wie de account aanmaakt.  Hoe kan ik jou uitnodigen voor een account?  Zet een betaling van een cent met je e-mail in de notitie?

**Comment by beninhos** [comment]
Zo zie ik hem ook staan.  Vaag. Ik zie bij mijn eigen gezamelijke rekening ook 2 eigenaren en kan die niet wijzigen.

**Comment by deltawessel** [comment]
Toch vreemd dat list_accounts.py hem wel ziet, maar populate niet.  Wat zie je als je de uitvoer van get_accounts() in lib/bunq_api.py afdrukt?  B.v. `log.info(self.bunq_accounts)` in lib/sync.py regel 62.

**Comment by beninhos** [comment]
ehm. Ik begrijp even niet zo goed hoe ik dat doe.  Kun je een voorbeeldje maken?

**Comment by deltawessel** [comment]
Sure, heb er een aparte branch voor gemaakt: https://github.com/wesselt/bunq2ynab/tree/logpopulate

**Comment by beninhos** [comment]
Hij heeft nu eerst een soort log van alle data die hij bij bunq ophaalt. Specifiek voor deze rekening zie ik dit lijstje:

` {'bunq_user_id': 580xxx, 'bunq_user_name': 'beninho', 'bunq_account_id': 827xxx, 'bunq_account_name': 'Gezamelijke rekening'`

Daarna gaat hij proberen te syncen op basis van mijn config.json

en dan zie ik

`WARNING | sync.py:92 | populate | No matches for rule "*" - "Gezamelijke rekening" to "April" - "Bunq - Gezamelijk".`

**Comment by deltawessel** [comment]
Als het goed is print hij ook de account lijst van YNAB.  Wat zie je daar?  (Of mail de output naar xxx als je dat prettiger vind)

**Comment by beninhos** [comment]
Solved. Just a type after all.

**Comment by beninhos** [comment]
closed
