### ISSUE TITLE
Automatische  sync werkt niet meer

### ISSUE THREAD

**Issue by Arnohappy** [wesselt/bunq2ynab#41]
Iets meer dan twee weken niet op YNAB gekeken. Zie ik tot mijn verbazing dat de auto sync voor het laatst heeft gewerkt op 29 mei. Hoe fix ik dit?

**Comment by wesselt** [comment]
Mogelijk is je developer token verlopen, dat is maar een half jaar geldig.

In de logging van het script zie je dit terug als 'Insufficient authorization".

**Comment by beninhos** [comment]
Ik heb ook zoiets: 

Jul 22 07:49:31 jaguar python3[1075]:   File "/pool/apps/bunq2ynab/lib/bunq.py", line 206, in get
Jul 22 07:49:31 jaguar python3[1075]:     return call('GET', method)
Jul 22 07:49:31 jaguar python3[1075]:   File "/pool/apps/bunq2ynab/lib/bunq.py", line 197, in call
Jul 22 07:49:31 jaguar python3[1075]:     raise Exception(result["Error"][0]["error_description"])
Jul 22 07:49:31 jaguar python3[1075]: Exception: Insufficient authentication.
Jul 22 07:49:31 jaguar python3[1075]: 2023-07-22 07:49:31,191 | ERROR | auto_sync.py:194 | <module> | Failed 130 times


Is dit nu de API aan bunqzijde of YNAB?

**Comment by beninhos** [comment]
python3 list_user.py geeft een foutmelding, dus blijkbaar is de bunq api ingetrokken. Vond het al gek, want ik heb het nog maar vanaf april de boel lekker draaien op autosync.

**Comment by wesselt** [comment]
Die melding betekent dat het bunq token verlopen is. Hoe werkt het met een nieuw bunq token?

**Comment by beninhos** [comment]
Yes, alles draait weer nu. Moest nog even de autosync herstarten. Heb daar trouwens een handig scriptje voor gemaakt via systemd. Kan ik dat ergens uploaden?

**Comment by wesselt** [comment]
Sure, je kan een pull request klaarzetten.  Of link hem (bv pastebin), dan zet ik hem erbij?

**Comment by beninhos** [comment]
Yes, heb een poging gedaan. Zit eingenlijk een stukje instructie en script bij. Misschien moet de instructie in de readme komen en het script als txt.

**Comment by wesselt** [comment]
Hmm, ik zie geen pull request: https://github.com/wesselt/bunq2ynab/pulls

In een pull request kan je ook een aanpassing van de readme klaarzetten :)

**Comment by beninhos** [comment]
Kijk, ik heb het hier gedaan. https://github.com/wesselt/bunq2ynab/commit/8cd1f834f283af70776c3177b25c96ae04ce2e06

of moet ik het eerst forken? Heb het nog niet eerder gedaan.

**Comment by wesselt** [comment]
Ja, geloof dat het zo werkt: forken, en dan maak je een nieuwe branch ("git branch <naam>") en die push je dan naar github.  Dan kan je een pull request aanmaken die ik kan accepteren.

Ik heb net zelf een pull request met jouw script gemaakt en gemerged: https://github.com/wesselt/bunq2ynab/pull/43
