### ISSUE TITLE
Bunq Child account are synced too

### ISSUE THREAD

**Issue by Drag0n** [wesselt/bunq2ynab#48]
Hi,

Is it possible to exclude some bunq accounts? I have created some child accounts that uses the same name as our main accounts. And those are synced to YNAB too. So all payments on both child accounts end up in our YNAB budgets.

**Comment by wesselt** [comment]
You can specify both the user and account name.  For example:

```
  "accounts": [
        {
          "bunq_account_name": "J. Jansen",
          "bunq_account_name": "rekening1",
          "ynab_budget_name": "mybudget",
          "ynab_account_name": "rekening1"
        }
    ]

```
Using list_user.py should show you the user name and account name.  If you provide both it should only sync one account.

How does this work for you?

**Comment by Drag0n** [comment]
I tried it, added "bunq_account_name": "xxxxxx". But it still synced the child accounts. I'm using AWS and don't know how to use list_user.py to show the user name and account.

EDIT: think I need to use the joint name, the CJ name. I tried it first with my own private user name. Keep you informed if this worked.

**Comment by Drag0n** [comment]
It still syncs. Can’t figure out what my user name is. As it’s a joint account. Tried everything. Is it possible to see somewhere?

**Comment by wesselt** [comment]
For me my username is in the Profile tab of the app, and then right below activity.

I see I put in the wrong name, it should be bunq_**user**_name instead of another bunq_account_name.

**Comment by Drag0n** [comment]
Well that would fix it I guess hahaha. Thnx

**Comment by Drag0n** [comment]
Still no luck, it is syncing all the child accounts too

**Comment by wesselt** [comment]
Hard to troubleshoot without the output from `list_user.py`.

Why not use different names for the child accounts?

**Comment by Drag0n** [comment]
I tried everything but no luck. How can I view the output of `list_user.py`?

And yes I changed the names of the accounts to unique names. So it doesn’t sync the other accounts.

Thanks anyway for you help and this excellent sync method ;) It’s a life changer

**Comment by wesselt** [comment]
If you only specify the YNAB budget name, it should sync all Bunq accounts it can read to YNAB accounts with the same name:

```
  "accounts": [
        {
          "ynab_budget_name": "mybudget"
        }
    ]
```

How does that work?
