### ISSUE TITLE
list_user not showing all of my accounts

### ISSUE THREAD

**Issue by SirCampsalot1611** [wesselt/bunq2ynab#52]
Since yesterday, when I sync my accounts its missing one subaccount of bunq. 
list_user.py shows all of my accounts, except this one.
Is this a known problem? 
The affected account is neither inactive nor frozen.

**Comment by wesselt** [comment]
Not a known problem. I know you can limit the accounts you can see with an oauth token.  You can check the current rights of an oauth token in Profile > Cogwheel > Security > My App Connections > Bank Accounts.

To troubleshoot, would you mind sharing the output of list_user with verbose enabled?  "list_user.py -v"

**Comment by Hammuts** [comment]
Same here, both for me and my partner. I'm a bit hesitant on sharing output here as it's full of personal information, but I can maybe run through it tonight/tomorrow and redact some stuff before I share. Anything else that might be helpful?

**Comment by SirCampsalot1611** [comment]
> Not a known problem. I know you can limit the accounts you can see with an oauth token.  You can check the current rights of an oauth token in Profile > Cogwheel > Security > My App Connections > Bank Accounts.
> 
> 
> 
> To troubleshoot, would you mind sharing the output of list_user with verbose enabled?  "list_user.py -v"

@wesselt  I dont use oauth token but API- Key to use bunq2ynab. So there is no entry for it.
I only have entries for a different app there. 

list_user.py only show 10 entries aka 10 subaccounts, active ones, frozen and inactive ones. But i have 12 accounts at bunq. Some of them are frozen / inactive some are not. 

Is it possible, there is newly a limit of 10 accounts that will be shown or synced? Eitherby the script or by bunq?

**Comment by SirCampsalot1611** [comment]
> Same here, both for me and my partner. I'm a bit hesitant on sharing output here as it's full of personal information, but I can maybe run through it tonight/tomorrow and redact some stuff before I share. Anything else that might be helpful?

@Hammerpawn 
How many subaccounts do you have at bunq?

**Comment by Hammuts** [comment]
> @Hammerpawn
How many subaccounts do you have at bunq?

@SirCampsalot1611 More than 10, indeed. Didn't know about the limit. I imagine something changed on bunq's side maybe, because I didn't download a new release or changed the config.

**Comment by SirCampsalot1611** [comment]
@Hammerpawn 
I don't know if there is a limit. This is only a guess.

**Comment by Hammuts** [comment]
@SirCampsalot1611 Is the sub-account that's not being shown an old one for you as well? For me it's one of the first ones I created, so it seems like the list is sorted based on creation date.

I wonder if it starts working again if i create a new sub-account and replace the old one, but I'm really not looking forward to reconfiguring all my automatic payments.

**Comment by SirCampsalot1611** [comment]
@Hammerpawn 
That could be possible,..its two accounts not getting displayed / synced. One of them - my "main" account, which I use for daily payments is for sure one the oldest.
The other one is an inactive account. Not sure if its the next - oldest, I created.

**Comment by Drag0n** [comment]
Don't know if it's the same issue but 6 of my sub accounts aren't synced to YNAB. 

Log says 
> WARNING | sync.py:90 | populate | No matches for rule etc........

Others are fine, and they have been synced untill yesterday. Nothing has been changed on my side.

**Comment by SirCampsalot1611** [comment]
> Don't know if it's the same issue but 6 of my sub accounts aren't synced to YNAB. 
> 
> 
> 
> Log says 
> 
> > WARNING | sync.py:90 | populate | No matches for rule etc........
> 
> 
> 
> Others are fine, and they have been synced untill yesterday. Nothing has been changed on my side.

Seems to be the same issue. Thats exactly the same message I get, when trying to sync. This log message makes absolutely sense, cause its trying to sync an account, which doesnt exist for the script.

**Comment by SirCampsalot1611** [comment]
@Drag0n you say, its 6 accounts not syncing. 
I am curios, how many accounts do you have in total, inactive/ frozen ones included?

**Comment by Drag0n** [comment]
> @Drag0n you say, its 6 accounts not syncing. I am curios, how many accounts do you have in total, inactive/ frozen ones included?

I have 9 sub accounts that’s been synced to YNAB.

**Comment by SirCampsalot1611** [comment]
> > @Drag0n you say, its 6 accounts not syncing. I am curios, how many accounts do you have in total, inactive/ frozen ones included?
> 
> 
> 
> I have 9 sub accounts that’s been synced to YNAB. 

Okay, so it sounds like its not a problem with limits

**Comment by Hammuts** [comment]
> @Drag0n you say, its 6 accounts not syncing. I am curios, how many accounts do you have in total, inactive/ frozen ones included?

>I have 9 sub accounts that’s been synced to YNAB.

@Drag0n Are these also the total number of accounts you have or had in the past though? I have only 4 that I sync to YNAB, but I still have more than 10 sub-accounts in bunq, although most are archived. How many do you see when you run list_user.py?

**Comment by SirCampsalot1611** [comment]
Even if you didnt ask me, i want to clarify / update my information: 

I have 12 subaccounts in bunq, some of them are inactive, some of them are active.
I only sync one of these 12 accounts - which does not work - log message "No matches for rule" appears.

When executing list_user.py it shows 10 accounts, the subaccount I want to sync actually ist not included.
This might be the reason, why the sync does not work - because the script does not find my account to sync.

The big question is now, why list_user.py / syncing does not find this account. 

I also asked bunq support, but didnt get a good answer yet.

**Comment by SirCampsalot1611** [comment]
> Not a known problem. I know you can limit the accounts you can see with an oauth token. You can check the current rights of an oauth token in Profile > Cogwheel > Security > My App Connections > Bank Accounts.
> 
> To troubleshoot, would you mind sharing the output of list_user with verbose enabled? "list_user.py -v"

@wesselt 
Ive saved the output of list_user with verbose enabled. Is there a way to send it to you without posting it here ?

**Comment by Bramjetten** [comment]
Seeing the same issue here, I quite a few subaccounts (>10) but I'm only seeing 10 subaccounts when I'm running list_user.py. My oldest accounts aren't being shown, looks like it's a change on bunq's end?

Edit:
Looks like it has something to do with pagination that changed. When manually adding `?older_id=[account_id]` to `bunq_api.py:102` it synced the older accounts.

**Comment by wesselt** [comment]
@SirCampsalot1611 How about sending an email to: bunq2ynab at aule.net

Pagination is interesting, there have been problems with that before.  If that is it I'd expect a Pagination element in the request for accounts.  I'll try to create a few test accounts myself.

**Comment by wesselt** [comment]
This quick fix works for me with 10+ accounts: https://github.com/wesselt/bunq2ynab/commit/2435ae11e48b29a69e6d0db35df9531220ae911b

**Comment by Bramjetten** [comment]
> This quick fix works for me with 10+ accounts: [2435ae1](https://github.com/wesselt/bunq2ynab/commit/2435ae11e48b29a69e6d0db35df9531220ae911b)

Worked like a charm!

**Comment by Hammuts** [comment]
> This quick fix works for me with 10+ accounts: https://github.com/wesselt/bunq2ynab/commit/2435ae11e48b29a69e6d0db35df9531220ae911b

Same here! Thanks for jumping on this so quickly ❤️

**Comment by SirCampsalot1611** [comment]
Your fix works for me. Great! Thanks alot!! ☺️
