### ISSUE TITLE
Noob question - update files on AWS

### ISSUE THREAD

**Issue by Drag0n** [wesselt/bunq2ynab#53]
Seeing some files are being edited/changed. How do you update those files running on AWS (Serverless). Was trying to fix the pagination error but think it's better to update all new files.

**Comment by wesselt** [comment]
I'm no expert in AWS either.  I remember it was possible to edit a "layer" and then a file. That's a lot of work.  The simplest fix might be to edit this call:

`method = "v1/user/{}/monetary-account".format(u["id"])`

And add "count=100":

`method = "v1/user/{}/monetary-account?count=100".format(u["id"])`

This should return 100 accounts so you're unlikely to need pagination.

Nick Strijbos might create a new AWS version, he offered so in this issue: https://github.com/wesselt/bunq2ynab/issues/49
