### ISSUE TITLE
No function

### ISSUE THREAD

**Issue by Arnohappy** [wesselt/bunq2ynab#54]
Ik moet het hele gebeuren weer opnieuw koppelen, maar ik krijg elke keer geen functie te zien.

**Comment by Arnohappy** [comment]
There is no data to display

**Comment by wesselt** [comment]
Goedemorgen Arno, wat bedoel je met "ik krijg elke keer geen functie te zien" ?

**Comment by Arnohappy** [comment]
Het staat allemaal netjes bij mijn applications, maar zodra ik op [Bunq2YnabFunction] klik staat er 'There is no data to display.'

**Comment by Arnohappy** [comment]
Ik kan alleen een nieuwe functie aanmaken

**Comment by wesselt** [comment]
Ah, dan neem ik aan dat je de AWS Serverless Application Store gebruikt.  Daar zit de verbetering niet in.

In dit ticket is aangegeven hoe je het makkelijk aan kan passen: https://github.com/wesselt/bunq2ynab/issues/53

Zoek deze call op (neem aan in lib/bunq_api.py):

`method = "v1/user/{}/monetary-account".format(u["id"])`

en voeg "count=100" toe:

`method = "v1/user/{}/monetary-account?count=100".format(u["id"])`

**Comment by Arnohappy** [comment]
Allright! Ga ik dat even proberen thanks!

**Comment by Arnohappy** [comment]
Oke sorry, ik dacht dat het allemaal iets makkelijker was. Hoe kan ik precies die call vinden? Ik werk vanaf de AWS serverless repo.

**Comment by wesselt** [comment]
Ik ben zelf niet goed thuis in AWS.  Ik herinner me dat je naar een "Layer" kon gaan, en daar de Python code kon bewerken met web editor.

**Comment by Arnohappy** [comment]
Maar de Python variant werkt wel gewoon? Anders ga ik die wel gebruiken.

**Comment by wesselt** [comment]
Ja, de laatste Python commit lost het issue op

**Comment by Arnohappy** [comment]
Check!

**Comment by Arnohappy** [comment]
Kan het kloppen dat er vandaag een nieuwe versie op AWS is geupload?

**Comment by wesselt** [comment]
Denk het wel, zie deze comment: https://github.com/wesselt/bunq2ynab/issues/49#issuecomment-1961328879

**Comment by Arnohappy** [comment]
Allright, helaas nog steeds hetzelfde probleem.

**Comment by wesselt** [comment]
Nick Strijbos heeft een [nieuwe AWS versie](https://eu-west-1.console.aws.amazon.com/lambda/home?region=eu-west-1#/create/app?applicationId=arn:aws:serverlessrepo:eu-west-1:167188378904:applications/bunq-ynab-aws-lambda) gemaakt.  Hoe werkt die?

**Comment by Arnohappy** [comment]
Ik heb Python nu draaien op een server en dat gaat prima! Kan dit helaas niet meer checken, maar wel goed dat het is aangepast voor de mensen die serverless draaien.
