### ISSUE TITLE
Bunq account missing

### ISSUE THREAD

**Issue by Thaboman** [wesselt/bunq2ynab#55]
Heja,

Running on a Raspberry Pi via auto sync, a few days ago one of my bank accounts stopped syncing. 

python3 list_user.py manages to find all my bank accounts expect one. 

Running a manual sync gives the error: WARNING | sync.py:90 | populate | No matches for rule "*"  (on that parcticular bank account)

It has worked in the past 2 weeks. 

I tried changing the bank account/ynab name to something else, sadly didn't work. 

Any idea what could be causing this? Any help is appreciated :)

**Comment by wesselt** [comment]
Yeah, something changed so pagination of the accounts is required.  A quick fix for that is committed to the master branch. https://github.com/wesselt/bunq2ynab/commit/2435ae11e48b29a69e6d0db35df9531220ae911b

 How does the latest version work for you?

**Comment by Thaboman** [comment]
ouch, that's quite the basic thing I skipped in troubleshooting.

Thanks! that did the trick
