### ISSUE TITLE
"Exception: Resolved host <old host from lambda installation> is invalid." after moving from lambda to python

### ISSUE THREAD

**Issue by metabubble** [wesselt/bunq2ynab#59]
```
2024-02-28 00:30:43,789 | INFO | bunq_api.py:61 | set_callbacks | Adding callback MUTATION:https://95.217.xxx.xxx:443/bunq2ynab-autosync
2024-02-28 00:30:44,107 | ERROR | auto_sync.py:221 | <module> | Bunq2ynab autosync error: Resolved host "n1vpkffdgj.execute-api.us-east-1.amazonaws.com." is invalid.
2024-02-28 00:30:44,107 | ERROR | auto_sync.py:222 | <module> | Traceback (most recent call last):
  File "/root/bunq2ynab/auto_sync.py", line 208, in <module>
    setup_callback()
  File "/root/bunq2ynab/auto_sync.py", line 135, in setup_callback
    bunq_api.add_callback(uid, marker, url)
  File "/root/bunq2ynab/lib/bunq_api.py", line 15, in add_callback
    set_callbacks(bunq_user_id, url_end, {
  File "/root/bunq2ynab/lib/bunq_api.py", line 68, in set_callbacks
    put_callbacks(bunq_user_id, new_callbacks)
  File "/root/bunq2ynab/lib/bunq_api.py", line 149, in put_callbacks
    bunq.post(method, data)
  File "/root/bunq2ynab/lib/bunq.py", line 235, in post
    return call('POST', method, data)
  File "/root/bunq2ynab/lib/bunq.py", line 210, in call
    raise Exception(result["Error"][0]["error_description"])
Exception: Resolved host "n1vpkffdgj.execute-api.us-east-1.amazonaws.com." is invalid.
```

I have created a fresh api key for bunq and a fresh api key for ynab.

I have `git clone https://github.com/wesselt/bunq2ynab.git` and modified my config.json. Manual sync works fine, however, when I `python3 auto_sync.py --port 443 --external-port 443 --refresh 60 --callback-host 95.217.xxx.xxx`, I get above mentioned error. I believe this is a previous callback url from when I used it with lambda, which went defunct.

**Comment by wesselt** [comment]
Hi metabubble, thanks for reporting.  The error comes from the bunq API. The `auto_sync.py` script works for me when I pass an IP address like you do.

I wonder where bunq gets the name n1vpkffdgj.execute-api.us-east-1.amazonaws.com.  Perhaps this is the reverse lookup for your IP.  What does `dig -x 95.217.xxx.xxx` show you? What does the `list_callbacks.py` script show?

**Comment by metabubble** [comment]
dig -x 

`136.237.xxx.xxx.in-addr.arpa. 86400 IN	PTR	static.136.237.xxx.xxx.clients.your-server.de.`

Not reverse dns

list_callbacks shows

```root@bunq2ynab:~/bunq2ynab# python3 list_callbacks.py 
Callbacks for user Christian Hawkins:
  MUTATION -> https://n1vpkffdgj.execute-api.us-east-1.amazonaws.com/bunq2ynab-lambda
  MUTATION -> https://9ie25u21jj.execute-api.eu-central-1.amazonaws.com/bunq2ynab-lambda
  MUTATION -> https://lst6nyps0b.execute-api.eu-central-1.amazonaws.com/bunq2ynab-lambda
Callbacks for account 12345678 (Accountname):
  No callbacks
Callbacks for account 12345678 (Accountname):
  No callbacks
Callbacks for account 12345678 (Accountname):
  No callbacks
Callbacks for account 12345678 (Accountname):
  No callbacks
Callbacks for account 12345678 (Accountname):
  No callbacks
Callbacks for account 12345678 (Accountname):
  MUTATION -> https://lst6nyps0b.execute-api.eu-central-1.amazonaws.com/bunq2ynab-lambda
```

**Comment by wesselt** [comment]
Ah, the way the API works is that you can only overwrite the list of callbacks.  So the script reads the old callbacks, adds a new callback, and posts them all.

What happens after you use `clear_callbacks.py` or `toggle_callbacks.py` to remove the existing callbacks?

**Comment by metabubble** [comment]
That was it. Old callbacks clogging up the account. Thank you, it is working again. I will delete the callbacks again and move back to lambda, as it is cheaper than a 4 euro vps :)
