### ISSUE TITLE
ERROR | lambda_function.py

### ISSUE THREAD

**Issue by Drag0n** [wesselt/bunq2ynab#61]
I get this error messsge:
| ERROR | lambda_function.py:62 | lambda_handler | Exceptions occurred

**Comment by nickstrijbos** [comment]
> I get this error messsge: | ERROR | lambda_function.py:62 | lambda_handler | Exceptions occurred

What kind of exception does is throw?

**Comment by Drag0n** [comment]
> > I get this error messsge: | ERROR | lambda_function.py:62 | lambda_handler | Exceptions occurred
> 
> What kind of exception does is throw?

Never mind, created a new API key in Bunq and it suddenly worked. I know you need to create a new Bunq API key once in a while but this one was 4 week old.

But thanks anyway ;)

**Comment by Drag0n** [comment]
Fixed
