### ISSUE TITLE
Emojis are not allowed in the account name

### ISSUE THREAD

**Issue by peterarends** [wesselt/bunq2ynab#7]
Not a big deal, renamed the accounts. Just wanted to let you know.

MonetaryAccountBank
Traceback (most recent call last):
  File "list_user.py", line 34, in <module>
    print_accounts(v["id"])
  File "list_user.py", line 27, in print_accounts
    v["id"]))
UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f60b' in position 15: ordinal not in range(128)

**Comment by wesselt** [comment]
Heb net getest met een rekening met emoji's erin en bij mij werkt het wel. Waarschijnlijk ligt het eraan dat je een ASCII terminal gebruikt. Wat is de uitvoer van:

`echo $LC_CTYPE`

Bij mij zegt dit "UTF-8".

**Comment by peterarends** [comment]
Dank voor je werk. Bij mij zegt de terminal ook "UTF-8".

**Comment by wesselt** [comment]
Bedankt voor de feedback. Da's vreemd, de foutmelding betekent dat Python iets naar een ASCII output probeert te schrijven. Maar jouw terminal is ook UTF-8.

Hoe draai je het script precies? Gebruik je misschien een redirect ("python list_user.py > logfile.txt") ?

**Comment by peterarends** [comment]
Geen probleem, jij ook bedankt. Nee gewoon in mijn iTerm2 ben ik ingelogd via ssh op mn Pi en daar doe ik direct het commando.
