### ISSUE TITLE
network.get_ip() should be network.get_public_ip()

### ISSUE THREAD

**Issue by peterarends** [wesselt/bunq2ynab#8]
File "/root/bunq2ynab/bunq.py", line 142, in register_device
    ip = network.get_ip()
AttributeError: module 'network' has no attribute 'get_ip'

**Comment by wesselt** [comment]
Thanks for reporting!  Fixed in https://github.com/wesselt/bunq2ynab/commit/91255b4dd1fa78096ab5351d937891e02921a7d7
